# Generated by Django 4.2.14 on 2024-08-07 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="about",
            old_name="update_on",
            new_name="updated_on",
        ),
    ]
