# Generated by Django 4.2.14 on 2024-08-07 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_rename_update_on_about_updated_on"),
    ]

    operations = [
        migrations.RenameField(
            model_name="about",
            old_name="text",
            new_name="context",
        ),
    ]
